# Generated by Django 6.0.3 on 2026-03-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
