# Generated by Django 6.0.3 on 2026-03-13 12:55

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_country_airport_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.image_upload_path
            ),
        ),
    ]
